<?php

namespace Database\Seeders;

use App\Models\Reel;
use Illuminate\Database\Seeder;

class ReelSeeder extends Seeder
{
    public function run(): void
    {
        $reels = [
            [
                'title' => 'Garage Build Reel #1 — Custom Setup',
                'car' => 'Universal / Workshop Build',
                'category' => 'Workshop Tuning',
                'tag' => '#REVVMOTIV',
                'video_path' => '/videos/reels/reel_1.mp4',
                'thumbnail_path' => null,
                'product_id' => 25,
                'caption' => "Live from the RevvMotiv tuning bay 🔥 Watch full installation and testing.\n\n#revvmotiv #carmods #tuning",
                'instagram_url' => 'https://www.instagram.com/revvmotiv/',
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'title' => 'Garage Build Reel #2 — Styling & Aero',
                'car' => 'Universal / Workshop Build',
                'category' => 'Aero & Styling',
                'tag' => '#MODIFIED',
                'video_path' => '/videos/reels/reel_2.mp4',
                'thumbnail_path' => null,
                'product_id' => 11,
                'caption' => "Precision fitment and aero styling directly from our workshop.\n\n#revvmotiv #styling #aerokits",
                'instagram_url' => 'https://www.instagram.com/revvmotiv/',
                'sort_order' => 2,
                'is_active' => true,
            ],
            [
                'title' => 'Garage Build Reel #3 — Lighting & Fitment',
                'car' => 'Universal / Workshop Build',
                'category' => 'Lighting & Styling',
                'tag' => '#CUSTOMCARS',
                'video_path' => '/videos/reels/reel_3.mp4',
                'thumbnail_path' => null,
                'product_id' => 6,
                'caption' => "Custom lighting setup and direct bolt-on fitment test.\n\n#revvmotiv #lighting #customcars",
                'instagram_url' => 'https://www.instagram.com/revvmotiv/',
                'sort_order' => 3,
                'is_active' => true,
            ],
            [
                'title' => 'Garage Build Reel #4 — Performance Parts',
                'car' => 'Universal / Workshop Build',
                'category' => 'Performance Parts',
                'tag' => '#CARMODS',
                'video_path' => '/videos/reels/reel_4.mp4',
                'thumbnail_path' => null,
                'product_id' => 20,
                'caption' => "High performance parts inspection and installation.\n\n#revvmotiv #carmods #tuningbay",
                'instagram_url' => 'https://www.instagram.com/revvmotiv/',
                'sort_order' => 4,
                'is_active' => true,
            ],
            [
                'title' => 'Garage Build Reel #5 — Aero Kit Fitting',
                'car' => 'Universal / Workshop Build',
                'category' => 'Aero Kits',
                'tag' => '#BODYKIT',
                'video_path' => '/videos/reels/reel_5.mp4',
                'thumbnail_path' => null,
                'product_id' => null,
                'caption' => "Complete body styling & aerodynamic kit test fit.\n\n#revvmotiv #bodykit #aero",
                'instagram_url' => 'https://www.instagram.com/revvmotiv/',
                'sort_order' => 5,
                'is_active' => true,
            ],
            [
                'title' => 'Garage Build Reel #6 — Workshop Tuning',
                'car' => 'Universal / Workshop Build',
                'category' => 'Workshop Tuning',
                'tag' => '#TRACKREADY',
                'video_path' => '/videos/reels/reel_6.mp4',
                'thumbnail_path' => null,
                'product_id' => null,
                'caption' => "Track-ready upgrades and custom tuning in action.\n\n#revvmotiv #trackready #garage",
                'instagram_url' => 'https://www.instagram.com/revvmotiv/',
                'sort_order' => 6,
                'is_active' => true,
            ],
            [
                'title' => 'Garage Build Reel #7 — Custom Exhaust & Aero',
                'car' => 'Universal / Workshop Build',
                'category' => 'Custom Exhaust & Aero',
                'tag' => '#REVVMOTIV',
                'video_path' => '/videos/reels/reel_7.mp4',
                'thumbnail_path' => null,
                'product_id' => null,
                'caption' => "Acoustic exhaust sound check & rear diffuser setup.\n\n#revvmotiv #exhaust #diffusers",
                'instagram_url' => 'https://www.instagram.com/revvmotiv/',
                'sort_order' => 7,
                'is_active' => true,
            ],
            [
                'title' => 'Garage Build Reel #8 — Diffusers & Spoilers',
                'car' => 'Universal / Workshop Build',
                'category' => 'Diffusers & Spoilers',
                'tag' => '#DIFFUSER',
                'video_path' => '/videos/reels/reel_8.mp4',
                'thumbnail_path' => null,
                'product_id' => null,
                'caption' => "Aggressive rear styling with custom diffuser fitting.\n\n#revvmotiv #spoilers #diffusers",
                'instagram_url' => 'https://www.instagram.com/revvmotiv/',
                'sort_order' => 8,
                'is_active' => true,
            ],
            [
                'title' => 'Garage Build Reel #9 — Custom Exterior',
                'car' => 'Universal / Workshop Build',
                'category' => 'Custom Exterior',
                'tag' => '#SPOILER',
                'video_path' => '/videos/reels/reel_9.mp4',
                'thumbnail_path' => null,
                'product_id' => null,
                'caption' => "Trunk lip spoilers & gloss black finishes.\n\n#revvmotiv #custom #aeroparts",
                'instagram_url' => 'https://www.instagram.com/revvmotiv/',
                'sort_order' => 9,
                'is_active' => true,
            ],
            [
                'title' => 'Garage Build Reel #10 — Lighting Setup',
                'car' => 'Universal / Workshop Build',
                'category' => 'Lighting Setup',
                'tag' => '#LIGHTING',
                'video_path' => '/videos/reels/reel_10.mp4',
                'thumbnail_path' => null,
                'product_id' => null,
                'caption' => "High intensity strobe & projector lighting install.\n\n#revvmotiv #lighting #foglights",
                'instagram_url' => 'https://www.instagram.com/revvmotiv/',
                'sort_order' => 10,
                'is_active' => true,
            ],
            [
                'title' => 'Garage Build Reel #11 — Aero Styling',
                'car' => 'Universal / Workshop Build',
                'category' => 'Aero Styling',
                'tag' => '#AEROPARTS',
                'video_path' => '/videos/reels/reel_11.mp4',
                'thumbnail_path' => null,
                'product_id' => null,
                'caption' => "Side skirts and front splitters installed with precision.\n\n#revvmotiv #splitters #sideskirts",
                'instagram_url' => 'https://www.instagram.com/revvmotiv/',
                'sort_order' => 11,
                'is_active' => true,
            ],
            [
                'title' => 'Garage Build Reel #12 — Garage Tuning',
                'car' => 'Universal / Workshop Build',
                'category' => 'Garage Tuning',
                'tag' => '#WORKSHOP',
                'video_path' => '/videos/reels/reel_12.mp4',
                'thumbnail_path' => null,
                'product_id' => null,
                'caption' => "Workshop inspection and quality checks.\n\n#revvmotiv #garage #tuning",
                'instagram_url' => 'https://www.instagram.com/revvmotiv/',
                'sort_order' => 12,
                'is_active' => true,
            ],
            [
                'title' => 'Garage Build Reel #13 — Workshop Showcase',
                'car' => 'Universal / Workshop Build',
                'category' => 'Workshop Showcase',
                'tag' => '#REVVMOTIV',
                'video_path' => '/videos/reels/reel_13.mp4',
                'thumbnail_path' => null,
                'product_id' => null,
                'caption' => "Final test and handover of custom tuned build.\n\n#revvmotiv #customcars #modified",
                'instagram_url' => 'https://www.instagram.com/revvmotiv/',
                'sort_order' => 13,
                'is_active' => true,
            ],
        ];

        // Replace / Seed all 13 reels cleanly
        Reel::truncate();
        foreach ($reels as $data) {
            Reel::create($data);
        }
    }
}
